# Generated by Django 4.0.3 on 2022-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='end_t',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ended_manually',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='start_t',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
