# Generated by Django 4.0.4 on 2022-04-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_is_closed_alter_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
